#!/usr/bin/env bash

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=~/.cache

mime_type=$(file --dereference --brief --mime-type -- "$file")

if [[ "$mime_type" == *"application/x-tar"* ]]; then
    tar tf "$file"
elif [[ "$mime_type" == *"application/zip"* ]]; then
    unzip -l "$file"
elif [[ "$mime_type" == *"application/x-rar"* ]]; then
    unrar l "$file"
elif [[ "$mime_type" == *"application/x-7z-compressed"* ]]; then
    7z l "$file"
elif [[ "$mime_type" == *"video/"* ]]; then
    thumbnail="$TEMPDIR/thumbnail.png"
    ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
    preview "$thumbnail"
elif [[ "$mime_type" == *"application/pdf"* ]]; then
    thumbnail="$TEMPDIR/thumbnail.png"
    gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    preview "$thumbnail"
elif [[ "$mime_type" == *"image/"* ]]; then
    preview "$file"
elif [[ "$mime_type" == *"font/"* ]]; then
    thumbnail="$TEMPDIR/thumbnail.png"
    fontpreview -i "$file" -o "$thumbnail"
    preview "$thumbnail"
elif [[ "$mime_type" == *"image/svg+xml"* ]]; then
    thumbnail="$TEMPDIR/thumbnail.png"
    convert "$file" "$thumbnail"
    preview "$thumbnail"
else
    batcat --style=plain --color=always --paging=never "$file"
fi

exit 127 # nonzero exit code required for lf previews to reload
